spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/db_shiro1
      # MySQLÈç¹ûÊÇ8.x   com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: admin123
      initial-size: 1
      min-idle: 1
      max-active: 20
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.qfedu.shiro3.beans
